### ISSUE TITLE
Bug in cf_ChiSquare.m

### ISSUE THREAD

**Issue by scholnik** [witkovsky/CharFunTool#8]
Lines 119 and 133 in `cf_ChiSquare.m` should both be
`if any(ncp~=0)`
instead of
`if ncp~=0`
which actually does
`if all(ncp~=0)`
This bug causes problems when some, but not all, of `ncp` is nonzero, and effectively sets `ncp` to all zeros.

**Comment by witkovsky** [comment]
Thank you very much for pointing to the issue... Viktor
